### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by Malapha** [orkblutt/MinerLamp#1]
This Project Looks nice :-) have been working with a powershell solution. Could you pls provide a compiled Version (win x64)?

**Comment by orkblutt** [comment]
Hi Malapha,

thanks for the comments.
YOu can find the last compiled version for Win64 here: https://github.com/orkblutt/MinerLamp/releases/latest

Feel free to report here any improvement suggestions or bugs.

Cheers

**Comment by Malapha** [comment]
Works -very nice !

With my mining it takes some time until the Cards Report positiv hashvalue. In my powershell script I implemented a var that defines the seconds until the real Monitoring starts (I need to set 0h/s at 80 now; if I can set a timer until Monitoring starts at 15 secs I could lower that number to 4-5). That way you can lower the max #0hs/s and capture other Errors faster. 

Small typo ("ehtminer") in line 199 mainwindow.cpp 

As you use $hashrate - you could implement a small moving avg. so hashrate would be more stable (Sum(last 10 hashrates)/10)

It doesn't seem to save Settings - so in case of a System restart or start at boot it's bit difficult to use...

All in all.. very well done!! Can't see any reason to use my powershell script any longer if Settings could be saved....

**Comment by Malapha** [comment]
btw. I wanted to enhence my script with some Basic stats of my minerpool (nanopool) through their api... so thats what i'll do next.. 

Some further thoughts - but not important - using nvidia-smi of the Nvidia installment, it should be possible to manipulate the Cards via commandline. So one could define a certain acceptable threshold "#Restarts /h" that optimizes those Settings (Optimize Mem MHz; Core MHz) until this threshold is reached.

Regards

**Comment by orkblutt** [comment]
Thanks for all these suggestions. I'll try to implement them soon!

**Comment by Malapha** [comment]
take your time... this tool seems to run very stable - compliments

**Comment by orkblutt** [comment]
Just added 2 options:
- autostart ethminer on Miner's Lamp startup
- add a delay before 0MH/s monitor start to check for the max 0Mh/s defined (as you suggested)

**Comment by Malapha** [comment]
Great - will test immediately

Result: Works as designed - now I can have max 5 x #0MHs/s with a 15 sec delay... Perfect. 

Another Question: If miner is stopped, ethminer as well as Miner's Lamp still go on as processes. Is it by purpose so you can start/stop for Debugging reasons? 

The "Start miner on Startup" is it meant to be used like this:

1) Startup Miners lamp
2) Configure
3) Start
4) Stop/Close -> Process runs on in Background
5) Startup miner again (double click the Exe) and Background process gets activated again?

Sry - just seen it's a placeholder so I'll let myself get surprised... I think the autostart Features needs the save Settings Feature to work properly. I'll edit my post at Issue #72 and direct/Support People to use your solution tomorrow. (sry. for the wrong uppercases words -> autocorrection)

Edit: edited my comment at Issue #72.

**Comment by Malapha** [comment]
Found a bug:

When Miner's Lamp restarts (due to cuda error) - the newly implemented delay is not used.

Same holds if you start/stop manually - so it seems to work just for the first time

**Comment by orkblutt** [comment]
Should be fixed now. Open a new issue if you see something similar.
