### ISSUE TITLE
Run several instances of MinerLamp with different command-line arguments

### ISSUE THREAD

**Issue by bdal69** [orkblutt/MinerLamp#10]
Hi Orkblutt.

Thanks for your work, it is really a nice tool.
I would like to be able to run several instances of MinerLamp, because I run the devices by groups
I created two folders with MinerLamp and tried to run each instances from each folder, but MinerLamps will alway have the settings from the last instance running. Anyway to have several instances running, each keeping its own settings when starting or restarting?

Thanks.

**Comment by orkblutt** [comment]
Hey bdal69,

I'm using QSettings to save/load settings. On Windows, it uses the registry to store the value. Using the same root key for each instance...
I could detect how much instances are already running and use a counter for key naming. I'll add it in the todo list.

**Comment by bdal69** [comment]
Thanks

**Comment by orkblutt** [comment]
Hi.
You can experiment to create several folder and put last minerlamp file in them... each minerlamp instance will store parameters from it's own minerlamp.ini file locating in same folder.
Let me know if it's ok for you.

**Comment by bdal69** [comment]
Hi,

I tried the multi-instances version.

It does not seem to create the minerlamp.ini file in my case. It seems to still take the parameters from the registry because it loaded with the parameters from the previous version. May be I should delete it from the registry first. I ran a seach on the registry but there are so many references to minerlamp that I don't know what to delete. Do you know where are stored these parameters in the registry?

**Comment by orkblutt** [comment]
Release issue... It's fixed now in the last .zip

**Comment by bdal69** [comment]
Very nice. 
Working fine, thanks
