### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ezspot** [orkblutt/MinerLamp#11]
Yo! Great work!  Some question. 

1. Could you explain abit more what the settings in GUI does. 
2. If i'm running multiple GPU, i would like to set witch to use.
So if card 0,1 crash it just restarts those cards, not everyone. 

I'm just running this .bat script now: 
`setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe -U -S eu1.ethermine.org:4444 -O 0xB69e57cAb06A4746.ethminer01
timeout 5
start-GPU0.bat`

3. Instead of command line, maybe it can use a .bat script already made?
4. Is there any loss in MH\s using this?

**Comment by orkblutt** [comment]
Hi spot88,

thanks for your comment.

1 - When the watchdog is checked, MinerLamp check automatically for the word "error" in the log output. It's also monitoring for 0.00MH/s. If ethminer produces more than "Max consecutive 0MH/s", minerlamp restart it. The option "Delay before monitoring for 0MHs" is usefull to avoid monitoring the first 0MHs at ethminer starts. The value is in seconds. The "Delay before restart", in seconds too, let a delay before to restart ethminer on error (error word, ethminer crash, max 0Mhs hit...).
The "Auto start miner" option starts ethminer at MinerLamp startup. 

2 - In this version MinerLamp support only 1 ethminer by instance. 

3 - Sure you can. But the stop button or watchdog will kill your script. Btw, the environnement variable settings are useless on nvidia cards .
4 - No. It's not pumping computation power from GPU. CPU impact isn't noticable neither.

**Comment by ezspot** [comment]
Cool, thanks for quick answer. Tryed this out last night, and seems to work well.

Atm. i'm just running Nvidia Cards, so the "setx" commands are not needed anyway?
Will you add support for more then 1 instance? Will this restart if it crashes? 
Maybe a compile guide?

**Comment by orkblutt** [comment]
Multi instances are NOW supported.
You can create 1 folder for each device and put minerlamp's file in them. It will use minerlamp.ini file to store/load parameters. So you can use differents options for each instances

**Comment by ezspot** [comment]
Just tested the new version you compiled,i don't see a minerlamp.ini? Do i need to create it myself? It seems to load my old parameters from the old version.

**Comment by ezspot** [comment]
Possible for a compile guide?, just a quick one.

**Comment by orkblutt** [comment]
Sorry! The last binary was outdated in the .zip.
I just published a new release to fix this issue.

I'll try to simplify the compile process. Then I'll do a quick guide.

**Comment by ezspot** [comment]
Awesome, Thanks! Keep up the good work.
