### ISSUE TITLE
IS it me or the HASHRATE not showing anymore

### ISSUE THREAD

**Issue by cnilsecure** [orkblutt/MinerLamp#12]
Hi,
I build myself and i tried to use the binary from release but I see 0.00 in hashrate?
is it a problem with my miner or its general problem? It used to be on the Windows title that also not working anymore

**Comment by orkblutt** [comment]
What version of ethminer do you use?

**Comment by cnilsecure** [comment]
latest directly from git

**Comment by orkblutt** [comment]
Can you please try with this one:
https://github.com/orkblutt/MinerLamp/releases/tag/v0.08

**Comment by cnilsecure** [comment]
@orkblutt mark it as closed it was my mistake.
I have a suggestion that will make your life easier and the users of course
instead of those 2 arg boxes for cmd and argument maybe you should make a config file and everything read from there.

**Comment by ezspot** [comment]
Agreed.

**Comment by orkblutt** [comment]
Do you have a format suggestion for this config file ?

**Comment by cnilsecure** [comment]
@orkblutt sure, config.ini
binaryminer=[path]   <--- if empty it will read it from current path ethminer.exe a.k.a default
arg=[arguments you want to run with]
watchdog=[1|0]
maxcon=[number]
delaymonitor=[number]
delayrestart=[number]
autostart=[1|0]
shareonly=[1|0]

**Comment by ezspot** [comment]
Or maybe enable\disable on the autostart,shareonly and watchdog. So you don't use numbers where it's not needed.

**Comment by cnilsecure** [comment]
@spot88 really doesnt matter whatever he find comfortable (1 and 0 is binary for on and off that's all)

**Comment by ezspot** [comment]
@cnilsecure I know that, and orkblutt know that :) - But for the rest of the peps, i think enable\disable would save him some support and question time :) This is just me thinking ahead, if he first decides to add it :D

**Comment by orkblutt** [comment]
I will store the config in minerlamp.ini in the same directory than the minerlamp.exe.
[General]
minerpath=d:\ethminer\build\ethminer\ethminer.exe
minerargs=-U -S ....
autorestart=true
max0mhs=2
restartdelay=5
zeromhsdelay=30
autostart=false
shareonly=true

But I let the GUI as it. Some people prefers using a GUI, some others edit the config file...
