### ISSUE TITLE
nvapi.h: No such file or directory

### ISSUE THREAD

**Issue by MRZA-MRZA** [orkblutt/MinerLamp#16]
Hello. I'm trying to compile MinerLamp on Ubuntu 17.04 but I ran into a problem:
```
$ make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -IC:/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v8.0/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o mainwindow.o mainwindow.cpp
In file included from nvocdialog.h:7:0,
                 from mainwindow.cpp:6:
nvidiaapi.h:8:19: fatal error: nvapi.h: No such file or directory
 #include "nvapi.h"
                   ^
compilation terminated.
Makefile:423: recipe for target 'mainwindow.o' failed
make: *** [mainwindow.o] Error 1
```
I can't find nvapi.h in any packages. I tried to download NVAPI from nvidia site but there is only Windows version.

**Comment by orkblutt** [comment]
Yes badly nVidia doesn't have a standar sdk for Windows and Linux.
On linux, there is no nvapi but a nvctrl sdk. I have not looked at it yet but I'll try as soon I finished to work on OC using nvapi on windows.
Actually you can comment all that part...
exclude from the project nvidiaapi.cpp/h and comment the include and call to nvapi in nvocdialog.h/.cpp

**Comment by MRZA-MRZA** [comment]
Thank you. I've successfully built it. Gonna test it soon.

**Comment by cnilsecure** [comment]
Can you share how you compiled it? I am having the same problem

**Comment by MRZA-MRZA** [comment]
@cnilsecure just do what orkblutt said. Edit project file and appropriate source files. I don't have diffs right now.

**Comment by gamaraan** [comment]
I've managed to build it. It will loose all the Nvidia hardware monitoring/overclocking, but it retains the ability to relaunch the process in case of errors.

I have attached a diff file. I hope @orkblutt will have time to look over nvctrl sdk and add this functions to the linux version soon (great work btw).

[minerlamp.zip](https://github.com/orkblutt/MinerLamp/files/1221933/minerlamp.zip)
