### ISSUE TITLE
Failure State Undetected

### ISSUE THREAD

**Issue by emily-pesce** [orkblutt/MinerLamp#17]
I had a failure where something crashed (I am guessing one of the GPUs) and ethminer started finding stale/incorrect nonces. Although I had the MinerLamp logging truncated to exclude the MH/s output, I am guessing all logging except for the "Solution Found" line stopped. Thus, I think MinerLamp failed to notice the crash and didn't restart. 

Brainstorming: two ways to detect: 
1) if no hash rate printed for X seconds then fail, or 
2) if multiple "Solution found" printed without corresponding stratum message (accepted or stale) then fail

![screenshot 2017-07-28 11 40 25](https://user-images.githubusercontent.com/2148735/28725373-3dec73fc-738b-11e7-960a-b7017bfa4557.jpg)

System is 7x RX470.

Running ethminer 0.12.0.dev1

**Comment by orkblutt** [comment]
Hey.
Too bad you checked "display only share info"... should have been nice to have the complete output.
Anyway, I will try to do something on this behaviour.

**Comment by orkblutt** [comment]
Hi  Michael,

It should be fixed in the last commit.
There is a new thread waiting for any hash rate.. if the delay is expired the ethminer process is restarted.
