### ISSUE TITLE
Version of Qt

### ISSUE THREAD

**Issue by ezspot** [orkblutt/MinerLamp#18]
Witch version of Qt do you use? Assume i have to have it to compile.

**Comment by orkblutt** [comment]
Hey I used the latest Qt version
https://info.qt.io/download-qt-for-application-development
You have to choose the open source one. I assume you have a compiler. The "easiest" way is to have Visual Studio installed (I use 2015 comunity).
Then you can open the minerlamp.pro in Qt Creator (the IDE).

**Comment by spot88** [comment]
Downloaded Qt Creator 4.3.1 (Community)
New Project -> Import Project -> Git Clone -> Repository:https://github.com/orkblutt/MinerLamp

**Comment by ezspot** [comment]
Get this error when i tryed to open the project:
`Running Windows Runtime device detection.
No winrtrunner.exe found.
Could not find qmake spec 'default'.
Error while parsing file C:\Users\spot\Documents\MinerLamp\MiningLigth.pro. Giving up.
Project ERROR: Cannot run compiler 'cl'. Maybe you forgot to setup the environment?
Error while parsing file C:\Users\spot\Documents\MinerLamp\MiningLigth.pro. Giving up.
Project ERROR: Cannot run compiler 'cl'. Maybe you forgot to setup the environment?
Error while parsing file C:\Users\spot\Documents\MinerLamp\MiningLigth.pro. Giving up.
Could not find qmake spec 'default'.
Error while parsing file C:\Users\spot\Documents\MinerLamp\MiningLigth.pro. Giving up.
Project ERROR: Cannot run compiler 'cl'. Maybe you forgot to setup the environment?
Error while parsing file C:\Users\spot\Documents\MinerLamp\MiningLigth.pro. Giving up.`

I'm on W10(64bit) btw.

**Comment by orkblutt** [comment]
Do you have visual studio (2015 community version) installed?

**Comment by ezspot** [comment]
@orkblutt Yes.
