### ISSUE TITLE
Add counter for restarts in main dashboard.

### ISSUE THREAD

**Issue by thghdbs** [orkblutt/MinerLamp#19]
A nice improvement would be to add a log or counter for restarts. With a counter Minerlamp would be perfect for figuring out the max overclock for each card.

**Comment by ezspot** [comment]
Counter is there already.

**Comment by thghdbs** [comment]
@spot88 thank you. I did not notice the counter on the window bar. Perhaps change this issue to an enhancement add the counter to the main dashboard view?

**Comment by ezspot** [comment]
I don't see the point of using time on adding this on the main dashboard? A log would be nice though.

**Comment by orkblutt** [comment]
Please open a new issue if you want a log file.
Let me know what do you want to be written on that log file.
