### ISSUE TITLE
Settings arent saved and autostart feature dont work

### ISSUE THREAD

**Issue by soerenwa** [orkblutt/MinerLamp#2]
If i reboot my rig the settings are lost. Seems like there is no config file which are saved? 
The "start miner on startup" feature wont start the program on windows start. If you mean on minerlamp startup i would highly interested in an autostartup feature for windows.

**Comment by orkblutt** [comment]
I fixed the problem in the last release. MinerLamp was saving parameters only on close (using the close menu in systray). Now it saves parameters on each changes.
https://github.com/orkblutt/MinerLamp/releases

For autostarting on windows you  need to  use windows registry to start MinerLamp.
http://www.pctools.com/guides/registry/detail/109/
+ the "start miner on startup" option on will start automatically ethminer using the  saved parameters.

**Comment by soerenwa** [comment]
Thanks working now for me! Btw the systray icon wont appear on my rigs..

**Comment by orkblutt** [comment]
systray should be fixed now

**Comment by Malapha** [comment]
yes works fine now
