### ISSUE TITLE
LED on share accepted (without overclocking)

### ISSUE THREAD

**Issue by thghdbs** [orkblutt/MinerLamp#20]
Would be very cool if the option to blink gpu LEDs on accepted share was separate from the overclock function. A possibility for this could be to have Minerlamp output audio on accepted share and use the nvidia LED visualizer to flash the LED on that sound.

**Comment by orkblutt** [comment]
I'm on it! :)

**Comment by ezspot** [comment]
@orkblutt Could i suggest to add fanzy "useless" stuff until it's perfect? :) Like the overlock that would be nice, ofc your time but just a tip. Love your GUI.

**Comment by orkblutt** [comment]
LED are now blinking. I'll take a look for the sound later (open an other issue if you want it)

**Comment by thghdbs** [comment]
@orkblutt FYI, Windows 10, 7 x 1070 Founders Edition GPUs running  v0.1.0.499 - enabling the LED flag turns LEDs off altogether. I had to run the nvidia LED visualizer to turn them back on.

**Comment by thghdbs** [comment]
@orkblutt following up on this. With v.537 and with the latest driver-supplied nvml the LED blinking now works.
