### ISSUE TITLE
GPU power and mem clock are not working

### ISSUE THREAD

**Issue by kirannminer** [orkblutt/MinerLamp#21]
Downloaded the latest version, looks like max power and memory clock feature are not working,I am using GTX 1060 3GB cards.

Can I ask you one enhancement, Could you please add share accepted and rejected as a separate tab in the main gui, I keep only share to be displayed.

I really love your gui, my mining was completely unstable, going pretty good with miner's lamp, Thanks for the great work.

**Comment by orkblutt** [comment]
hey,

can you try:
- stop minerlamp
- copy your nvml.dll from your C:\Program Files\NVIDIA Corporation\NVSMI\
- paste it in your MinerLamp's folder
- start minerlamp

Can you say me if it resolve your issue?

**Comment by kirannminer** [comment]
yes , this fixed the issue, Thank you.

Looks like miner's lamp was crashed , not sure, what happened, I am still doing the testing, may be high CPU usage or so. will let you know.

**Comment by orkblutt** [comment]
please open an other issue if the problem persists.
thanks
