### ISSUE TITLE
Hang Issue

### ISSUE THREAD

**Issue by ezspot** [orkblutt/MinerLamp#23]
Referring to this on your update?
![71b71354ed14a3a7feb643941efa052a](https://user-images.githubusercontent.com/10884072/28939165-a346ca36-7890-11e7-90f0-2f6268c5521b.png)

**Comment by thghdbs** [comment]
I ran into this problem when I had an extra space at the end of the batch script string.

As an enhancement, perhaps escape out trailing spaces in the entry field?

**Comment by orkblutt** [comment]
Yes... it should be fixed now!
