### ISSUE TITLE
Still having hang out

### ISSUE THREAD

**Issue by khaman1** [orkblutt/MinerLamp#25]
I'm sorry but Minerlamp is still making my 2/3 rigs hang out. I don't know why they hang but just let you know that.

**Comment by orkblutt** [comment]
Hey,

sorry I cannot look in detail actually (vacations). MinerLamp is not freezing your RIG. I think is more your OC settings or the device/driver having a problem than MinerLamp... Can you provide more details please?

**Comment by khaman1** [comment]
My rig is still hang out. The console output was a list of ethminer start and ethminer exit. Probably you didn't clearn out completely the old work to make a new restart so that it seems like the program have had restart but did nothing.

**Comment by khaman1** [comment]
Hello orkblutt,
It's nice to have a windows restart if there is a sequence of "ethminer start" and "ethminer exit" like 5 or 6 times continuously.
