### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by Malapha** [orkblutt/MinerLamp#28]
I noticed a significant increase in cpu usage. Miner's Lamp uses nearly constantly 1 core (out of 4). Haven't noticed this with earlier Versions. 

![image](https://user-images.githubusercontent.com/30199411/29051714-ec89a4aa-7be4-11e7-9313-c8fcf40479ab.png)

edit: Seems to be related to afterburner. When overclocking too much, afterburner hangs - somehow then also minerlamp uses more cpu power..

**Comment by ezspot** [comment]
Afterburner sucks balls atm, my comp hangs regulary.

**Comment by soerenwa** [comment]
it isnt minerslamp. Ethminer with msafterburner.exe open seems to produce this error. Just get a little script which kills msiafterburner after 1min. Hopefully we get minerlamp oc soon ;)
