### ISSUE TITLE
DONATION should be advertised in releases

### ISSUE THREAD

**Issue by kiwina** [orkblutt/MinerLamp#30]
Hi you should really advertise that there is donation enabled in the releases!!!!!!!

**Comment by orkblutt** [comment]
Yes you're right. I have to update the readme. I'll do that before the end of the day.

**Comment by orkblutt** [comment]
done.

**Comment by ezspot** [comment]
Has this been there all the time????

**Comment by orkblutt** [comment]
No since 15 days... I commited this change just before to go on vacations... I didn't planed to loose internet access during my trip and the plan was to inform users asap
