### ISSUE TITLE
Crash when donate kicks in

### ISSUE THREAD

**Issue by hpolthof** [orkblutt/MinerLamp#32]
I don't mind to donate, cause I like your tool.

But everytime the donation run kicks in the miner crashes. Miner is not able to connect to pool or has a DAG problem.

You should think of mining the donation on something else than Ethereum. The DAG size is over 2G and older cards will crash. On my older rigs I'm currently mining Expanse and Ubiq. Those have smaller DAG sizes and will not crash.

Had to switch back to just using genoil and ended up writing my own watchdog script.

**Comment by ezspot** [comment]
@hpolthof Mind sharing your watchdog script?

**Comment by orkblutt** [comment]
I will release this weekend a new version with the donate as a checkable option.

**Comment by orkblutt** [comment]
Hi,
You can find this option in the latest release:

https://github.com/orkblutt/MinerLamp/releases/tag/v0.1.2.0

Go on the "about" button and check/uncheck the donate checkbox...

You need the latest version of etherminer, the one with that kind of output:
"m 00:32:24|main Speed 32.80 Mh/s gpu/0 32.80 [A478+2:R0+0:F0]"

This version also include some overclocking options tested only on a 1070 GTX at the moment.

**Comment by orkblutt** [comment]
@hpolthof can we close this issue?
