### ISSUE TITLE
Hi Orkblutt

### ISSUE THREAD

**Issue by aliceaia** [orkblutt/MinerLamp#33]
Can this application run in a non-GUI version?

**Comment by orkblutt** [comment]
Hi Aliceaia,
the design of the app can't be easily adapted to run in a non-GUI application.
I could start it minimized (in the systray) by adding an option if you like.

**Comment by aliceaia** [comment]
Thank you. I want to run the application on ubuntu, but maybe this is not feasible.

**Comment by orkblutt** [comment]
Only on your favorite desktop (Gnome, KDE or others)...
If you run ethminer in pure command line there are plenty of nice bash scripts around to monitor the miner.

**Comment by aliceaia** [comment]
Can you please help me?

**Comment by orkblutt** [comment]
Come on gitter: https://gitter.im/MinerLamp/Lobby
