### ISSUE TITLE
Support ethminer 0.12.0rc1 Format

### ISSUE THREAD

**Issue by airbreather** [orkblutt/MinerLamp#37]
[ethminer 0.12.0rc1](https://github.com/ethereum-mining/ethminer/releases/tag/v0.12.0rc1) was just released a few hours ago (as of time of writing).  Its new output format isn't recognized by MinerLamp.

**Comment by airbreather** [comment]
Sample output when run inside MinerLamp with my 2 GTX 1070s:

```
m 07:50:58|main Speed 53.48 Mh/s gpu/0 26.21 gpu/1 27.26 [A1+0:R0+0:F0]
m 07:51:00|main Speed 55.57 Mh/s gpu/0 27.26 gpu/1 28.31 [A1+0:R0+0:F0]
m 07:51:02|main Speed 54.53 Mh/s gpu/0 26.21 gpu/1 28.31 [A1+0:R0+0:F0]
m 07:51:04|main Speed 54.53 Mh/s gpu/0 27.26 gpu/1 27.26 [A1+0:R0+0:F0]
m 07:51:06|main Speed 54.53 Mh/s gpu/0 26.21 gpu/1 28.31 [A1+0:R0+0:F0]
```

**Comment by aliceaia** [comment]
ethminer 0.12.0rc1 still display the old style version dev2

**Comment by aliceaia** [comment]
Please point out the wrong display on the minerlamp

**Comment by airbreather** [comment]
I'm using release [Fix for new ethminer output format (hashrate by device)](https://github.com/orkblutt/MinerLamp/releases/tag/v0.1.0.620).

Note the hashrate reported in the log box below being nonzero, but the big numbers say 0:

![image](https://user-images.githubusercontent.com/3792815/30113953-4fa10ee6-92e4-11e7-8c20-926ba8a07857.png)

**Comment by aliceaia** [comment]
I understand. If you need I can compile a quick copy to show the hashrate.

**Comment by airbreather** [comment]
>I understand. If you need I can compile a quick copy to show the hashrate.

I'm not in a hurry to get a fix.  Thanks, though.

**Comment by aliceaia** [comment]
OK. I usually only choose to show shares so I do not care about other metrics. Even the ethminer version on linux I have just retained the shares index and error messages.

**Comment by orkblutt** [comment]
Hi Joe,

can you try the last minerlamp release please?
https://github.com/orkblutt/MinerLamp/releases
Thanks

**Comment by ilovelobster** [comment]
Works for me, I was having the same issue as him - this is working on the latest release: https://github.com/ethereum-mining/ethminer/releases/tag/v0.12.0rc1

BTW a couple spelling mistakes:

1. ' "Delay" before no hash: '
2. Hover over big numbers/alt tag: ' "Displaying" the current hashrate. '

Also if you're looking to fancy this up, I am a UI designer and can redesign the front end if you're interested.

Cheers and thanks for your effort!

**Comment by orkblutt** [comment]
@ilovelobster thanks for the spelling mistakes.
I'm very interested by a nice redesign! Are you familiar with Qt Creator or you can propose me some mokeup ?

**Comment by ilovelobster** [comment]
@orkblutt Not familiar with Qt creator... though I just googled it so I will take a look at sometime this week - it looks straightforward and easy enough to learn. I'll try to come up with something this week!

**Comment by airbreather** [comment]
> Hi Joe,
> 
> can you try the last minerlamp release please?
> https://github.com/orkblutt/MinerLamp/releases
> Thanks

It works.  Sorry for not trying the latest before.
