### ISSUE TITLE
Latest MinerLamp not working with ethminer 0.12.0rc2

### ISSUE THREAD

**Issue by mrmishmash** [orkblutt/MinerLamp#39]
Hello,
the latest release of MinerLamp is currently not working with ethminer 0.12.0rc2, When MinerLamp is started, I get the following output:

> ethminer started
> ethminer stopped

and that keeps repeating. Hopefully you can make it work with the RC2 release soon. I love what you are doing!

**Comment by orkblutt** [comment]
Hey,

I'll fix this issue asap today. I'll let you know

**Comment by orkblutt** [comment]
can you try this release https://github.com/orkblutt/MinerLamp/releases/tag/v0.1.2.32

**Comment by mrmishmash** [comment]
I tried it and it does work *sometimes* but not always. I tried restarting it a few times and on the 5th try it did work, but most of the time it just gives me the output as shown on the image. Thanks for the lightning fast response mate! 

![image](https://user-images.githubusercontent.com/11272843/30379334-7243cada-9896-11e7-80e3-35fdd708ae2f.png)

**Comment by orkblutt** [comment]
Can you uncheck the "Only display share info" and see if you don't have a real problem with ethminer?

**Comment by mrmishmash** [comment]
Sure, I did that and it does the same thing. ethminer works fine on its own. I am appending the output I received [in this Gist](https://gist.github.com/mrmishmash/727df91ea1f482784416c71a52ce0ccb).

**Comment by orkblutt** [comment]
You should maybe increase the "Delay before no hash"... Try to set it to 60 s

**Comment by mrmishmash** [comment]
Seems to be working now. I'll keep it running for the day and if all goes well I'll close this issue. Thank you for the assistance.
