### ISSUE TITLE
Reapply Overclocking

### ISSUE THREAD

**Issue by Malapha** [orkblutt/MinerLamp#4]
Another Idea.

sometimes  when CUDA error comes, my overclock Settings get reset. I use MSI Afterburner with profiles.

I found a Switch for that, so profiles can be loaded and applied via commandline.

So - having another Path/Exec Var pointing to MSI Afterburner plus an Integer (1-5) one could force Afterburner to reload a given Profile after a CUDA Crash..

MSIAfterburner.exe /Profile[1-5]

**Comment by orkblutt** [comment]
The easy way should to pass to MinerLamp a script in the miner path
In that script you run your OC settings and then call ethminer with the good parameters
Just avoid the term "error" in the output of your OC settings because MinerLamp will catch it and will restart your script over and over...

**Comment by orkblutt** [comment]
I'll probably add a better way later in MinerLamp

**Comment by Malapha** [comment]
Applying the afterburner Profile now via a small script:

minerlamp.ps1

````
function EthRestart{
         Start-Process .\minerlamp\run.bat
}

$ethstartdate=get-date
$jobstartdate= Get-Date
$nowdate = Get-Date
Start-Process .\minerlamp\run.bat
$f=0
while($f -eq 0) { 
        sleep 10
  $nowdate= Get-Date

#after 12hours restart minerlamp/ethminer and apply afterburnersettings
  if(($nowdate - $ethstartdate).totalseconds -ge 43200) {
        ethrestart
        $ethstartdate= Get-Date
        $jobstartdate=$nowdate        
   }
}
exit

````

run.bat
````
"C:\Program Files (x86)\MSI Afterburner\"msiafterburner.exe /profile3
Exit
````

**Comment by soerenwa** [comment]
Is there any other option to set the pwt and mem/core clock on startup? Afterburner with ethminer causing high cpu usage and lagging/freezing. Currently running a workaround with taskkill which seems to work ok. But any tips with another approach would be great ;-). An integration in minerlamp would be awsome aswell :D

**Comment by orkblutt** [comment]
I'm looking to integrate OC directly in MinerLamp. As you can sse in the last release, it's already interacting with nvidia's driver using NVML (as nvidia-smi does). I hope to find time to work on it this week.

**Comment by orkblutt** [comment]
A bit longer to make it work... still on it

**Comment by orkblutt** [comment]
@Malapha can you test the latest version please?

**Comment by Malapha** [comment]
Hi Orkblutt,

 

I switched back to claymore as my rig changed to a mixed set amd/nvidia. Handling was easier that way, as I went into holidays..

 

Of cause I still have all the configs, so I can check it in a view days..

 

Regards

 

Von: orkblutt [mailto:notifications@github.com] 
Gesendet: Samstag, 2. September 2017 10:08
An: orkblutt/MinerLamp <MinerLamp@noreply.github.com>
Cc: Malapha <lurgenprinz@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [orkblutt/MinerLamp] Reapply Overclocking (#4)

 

@Malapha <https://github.com/malapha>  can you test the latest version please?

**Comment by orkblutt** [comment]
done
