### ISSUE TITLE
Hashrates are low

### ISSUE THREAD

**Issue by moljach** [orkblutt/MinerLamp#40]
I have finally make the program work but the hash rate is very low.. it's saying like 12 mh/s per GPU... Why is that?

![watchdog](https://user-images.githubusercontent.com/31963739/30437497-0f88caec-996f-11e7-94bd-ce49632852d7.png)

**Comment by orkblutt** [comment]
What are your GPU ? What ethminer build? What's your driver version?

**Comment by moljach** [comment]
I have asus p106-100. Ethminer 0.12.0rc2.. The drivers from gpu official website(382.53)

**Comment by orkblutt** [comment]
Did you solve your issue? I don't think this is linked to MinerLamp itself.
