### ISSUE TITLE
Limit Log Output

### ISSUE THREAD

**Issue by Malapha** [orkblutt/MinerLamp#6]
Wondering what happens to Memory consumption if minerlamp runs for longer periods. I think is would be good to limit the displaymemory (where the log is shown)?

**Comment by orkblutt** [comment]
After some monitoring of the mem use after 3 or 4 days running I didn't noticed a big growup.
I don't know exactly how Qt manages it but looks pretty good. Let me know if you notice a growing memory usage. I'll check if can do something.

**Comment by Malapha** [comment]
ok

**Comment by orkblutt** [comment]
Hi,
any news regarding this potential issue?

**Comment by Malapha** [comment]
no... mem usage is very stable.. can be closed
