### ISSUE TITLE
Many rejects

### ISSUE THREAD

**Issue by cnilsecure** [orkblutt/MinerLamp#8]
Hi,

Good work!!, but i noticed in linux when i use minerlamp it have many many rejects (dwarfpool)
when i use command line much much less reject if any (I have no idea why its happening)
another small issue is when submitting stale share it does not consider this as failure therefore will not restart the miner (can be fixed?)

**Comment by orkblutt** [comment]
Hi cnilsecure,
I didn't tested yet on Linux. I really don't understand why it could generate rejects on dwarfpool. Can you run on a longer sample with and without minerlamp to have some stats ?

I don't consider a stale as an error. You will loose time to restart your miner for nothing (it won't resolve the last stale or decrease your futur stale rate...)
