### ISSUE TITLE
Missing ETHminer DLL's

### ISSUE THREAD

**Issue by mmurfy** [orkblutt/MinerLamp#9]
Hi, when I run minerlamp.exe it wont open the gui and I get windows system error saying the ETHminer dlls are not found for example --> vcruntime140, msvcp140. I have minerlamp running on another PC no problem and I copied the full directory onto another PC but it won't run, windows throws the error messages. I deleted the copied over version and extracted from the zip but it still won't run still get the errors.

Any ideas?

thanks

**Comment by orkblutt** [comment]
Hi mmurfy,

you need the visual studio redistribuable:
https://www.microsoft.com/en-US/download/details.aspx?id=53587

cheers

**Comment by orkblutt** [comment]
Also, you need the nvml.dll in your PATH or in the same folder.

**Comment by mmurfy** [comment]
work thanks
